name       : qscintilla
version    : '2.10'
release    : 4
source     :
    - https://versaweb.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10/QScintilla_gpl-2.10.tar.gz : 16be30577bc178470936c458551f2512cc068aff6e7a7de6ed244e28c045f6ec
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(QtCore)
setup      : |
    cd Qt4Qt5
    qmake-qt4 QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4
build      : |
    cd Qt4Qt5
    %make
install    : |
    cd Qt4Qt5
    %make_install INSTALL_ROOT=$installdir
    %qmake
    %make
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - qt5:
        - /usr/lib64/*qt5.so.*
        - /usr/share/qt5
    - qt5-devel:
        - /usr/include/Qsci/*
        - /usr/lib64/*qt5.so
