name       : qscintilla
version    : 2.11.6
release    : 9
source     :
    - https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.11.6/QScintilla-2.11.6.tar.gz : e7346057db47d2fb384467fafccfcb13aa0741373c5d593bc72b55b2f0dd20a7
homepage   : https://www.riverbankcomputing.com/software/qscintilla/
license    : GPL-3.0-only
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
replaces   :
    - devel : qscintilla-qt5-devel
    - qscintilla-qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    pushd Qt4Qt5
    %qmake
build      : |
    %make -C Qt4Qt5
install    : |
    %make_install -C Qt4Qt5 INSTALL_ROOT=$installdir
