name       : qscintilla
version    : 2.9.4
release    : 5
source     :
    - https://superb-sea2.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.9.4/QScintilla_gpl-2.9.4.tar.gz : 8b3a23023e9f0573caed6f9cee86f898d87b768ee15b8c211a423783a4cfa4e6
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(QtCore)
setup      : |
    cd Qt4Qt5
    qmake-qt4 QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4

build      : |
    cd Qt4Qt5
    %make
install    : |
    cd Qt4Qt5
    %make_install INSTALL_ROOT=$installdir
    
    make clean

    sed -i "s|-lqscintilla2|-lqscintilla2-qt5|g" features/qscintilla2.prf
    sed -i "s|qscintilla2|qscintilla2-qt5|g" qscintilla.pro
    %qmake
    %make
    %make_install INSTALL_ROOT=$installdir
patterns   :
    - qt5 :
        - /usr/lib64/*qt5.so.*
        - /usr/share/qt5
    - qt5-devel :
        - /usr/include/Qsci/*
        - /usr/lib64/*qt5.so
