name       : qscintilla
version    : 2.9.4
release    : 3
source     :
    - https://cytranet.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.9.4/QScintilla_gpl-2.9.4.tar.gz : 8b3a23023e9f0573caed6f9cee86f898d87b768ee15b8c211a423783a4cfa4e6
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(QtCore)
setup      : |
    cd Qt4Qt5
    qmake-qt4 qscintilla.pro \
              QMAKE_MOC=/usr/bin/moc-qt4 \
              QMAKE_RCC=/usr/bin/rcc-qt4 \
              QMAKE_UIC=/usr/bin/uic-qt4
build      : |
    cd Qt4Qt5
    %make
install    : |
    cd Qt4Qt5
    %make_install INSTALL_ROOT=$installdir
