name       : qscintilla
version    : 2.10.2
release    : 6
source     :
    - https://superb-sea2.dl.sourceforge.net/project/pyqt/QScintilla2/QScintilla-2.10.2/QScintilla_gpl-2.10.2.tar.gz : 14b31d20717eed95ea9bea4cd16e5e1b72cee7ebac647cba878e0f6db6a65ed0
license    : GPL-3.0
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
patterns   :
    - qt5 :
        - /usr/lib64/*qt5.so.*
        - /usr/lib64/qt5/mkspecs
        - /usr/share/qt5
    - qt5-devel :
        - /usr/include/Qsci/*
        - /usr/lib64/*qt5.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(QtCore)
setup      : |
    cd Qt4Qt5
    qmake-qt4 QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4
build      : |
    %make -C Qt4Qt5
install    : |
    cd Qt4Qt5
    %make_install INSTALL_ROOT=$installdir
    make clean

    %qmake
    %make
    %make_install INSTALL_ROOT=$installdir

