name       : qscintilla
version    : 2.13.1
release    : 10
source     :
    - https://www.riverbankcomputing.com/static/Downloads/QScintilla/2.13.1/QScintilla_src-2.13.1.tar.gz : 800e3d2071a96bcccd7581346af0d2fe28fc30cd68530cb8302685d013afd54a
homepage   : https://www.riverbankcomputing.com/software/qscintilla/
license    : GPL-3.0-only
component  : programming
summary    : QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control
description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
replaces   :
    - devel : qscintilla-qt5-devel
    - qscintilla-qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    pushd src
    %qmake
build      : |
    %make -C src
install    : |
    %make_install -C src INSTALL_ROOT=$installdir
